name: School News Bot
on:
  repository_dispatch:
    types: [check_news]
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          pip install requests beautifulsoup4
          python scraper.py
      - name: Save
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add *.txt
          git commit -m "Update" || exit 0
          git push
